env = Environment(PIC='24FJ128GB206',
                  CC='xc16-gcc',
                  PROGSUFFIX='.elf',
                  CFLAGS='-g -omf=elf -x c -mcpu=$PIC',
                  LINKFLAGS='-omf=elf -mcpu=$PIC -Wl,--script="app_p24FJ128GB206.gld"',
                  CPPPATH='../lib')
env.PrependENVPath('PATH', '/opt/microchip/xc16/v1.25/bin')

bin2hex = Builder(action='xc16-bin2hex $SOURCE -omf=elf',
                  suffix='hex',
                  src_suffix='elf')
env.Append(BUILDERS={'Hex': bin2hex})
list = Builder(action='xc16-objdump -S -D $SOURCE > $TARGET',
               suffix='lst',
               src_suffix='elf')
env.Append(BUILDERS={'List': list})

env.Program('haptic', ['haptic.c',
                         '../lib/common.c',
                         '../lib/usb.c',
                         'usb_descriptors.c',
                         '../lib/timer.c',
                         '../lib/ui.c',
                         '../lib/pin.c',
                         '../lib/spi.c',
                         '../lib/oc.c',
                         '../lib/uart.c',
                        ]
           )

env.Program('haptic_spring', ['haptic_spring.c',
                         '../lib/common.c',
                         '../lib/usb.c',
                         'usb_descriptors.c',
                         '../lib/timer.c',
                         '../lib/ui.c',
                         '../lib/pin.c',
                         '../lib/spi.c',
                         '../lib/oc.c',
                         '../lib/uart.c',
                        ]
           )

env.Program('haptic_damper', ['haptic_damper.c',
                         '../lib/common.c',
                         '../lib/usb.c',
                         'usb_descriptors.c',
                         '../lib/timer.c',
                         '../lib/ui.c',
                         '../lib/pin.c',
                         '../lib/spi.c',
                         '../lib/oc.c',
                         '../lib/uart.c',
                        ]
           )

env.Program('haptic_wall', ['haptic_wall.c',
                         '../lib/common.c',
                         '../lib/usb.c',
                         'usb_descriptors.c',
                         '../lib/timer.c',
                         '../lib/ui.c',
                         '../lib/pin.c',
                         '../lib/spi.c',
                         '../lib/oc.c',
                         '../lib/uart.c',
                        ]
           )

env.Program('haptic_texture', ['haptic_texture.c',
                         '../lib/common.c',
                         '../lib/usb.c',
                         'usb_descriptors.c',
                         '../lib/timer.c',
                         '../lib/ui.c',
                         '../lib/pin.c',
                         '../lib/spi.c',
                         '../lib/oc.c',
                         '../lib/uart.c',
                        ]
           )

env.Program('control', ['control.c',
                         '../lib/common.c',
                         '../lib/usb.c',
                         'usb_descriptors.c',
                         '../lib/timer.c',
                         '../lib/ui.c',
                         '../lib/pin.c',
                         '../lib/spi.c',
                         '../lib/oc.c',
                         '../lib/uart.c',
                        ]
           )


env.Program('how_to_usb', ['how_to_usb.c',
                         '../lib/common.c',
                         '../lib/usb.c',
                         'usb_descriptors.c',
                         '../lib/timer.c',
                         '../lib/ui.c',
                         '../lib/pin.c',
                         '../lib/uart.c',
                        ]
           )


env.Hex('haptic')
env.Hex('haptic_spring')
env.Hex('haptic_damper')
env.Hex('haptic_texture')
env.Hex('haptic_wall')
env.List('haptic')
env.Hex('control')
env.List('control')
env.Hex('how_to_usb')
env.List('how_to_usb')